// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: proto/brb/v1/brb.proto

package brbv1

import (
	_ "github.com/relab/gorums"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BroadcastID scopes protocol state to one value proposed by one origin.
type BroadcastID struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Origin   uint32                 `protobuf:"varint,1,opt,name=origin"`
	xxx_hidden_Sequence uint64                 `protobuf:"varint,2,opt,name=sequence"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BroadcastID) Reset() {
	*x = BroadcastID{}
	mi := &file_proto_brb_v1_brb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastID) ProtoMessage() {}

func (x *BroadcastID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brb_v1_brb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BroadcastID) GetOrigin() uint32 {
	if x != nil {
		return x.xxx_hidden_Origin
	}
	return 0
}

func (x *BroadcastID) GetSequence() uint64 {
	if x != nil {
		return x.xxx_hidden_Sequence
	}
	return 0
}

func (x *BroadcastID) SetOrigin(v uint32) {
	x.xxx_hidden_Origin = v
}

func (x *BroadcastID) SetSequence(v uint64) {
	x.xxx_hidden_Sequence = v
}

type BroadcastID_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Origin   uint32
	Sequence uint64
}

func (b0 BroadcastID_builder) Build() *BroadcastID {
	m0 := &BroadcastID{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Origin = b.Origin
	x.xxx_hidden_Sequence = b.Sequence
	return m0
}

// PhaseMessage carries the value associated with a broadcast instance.
type PhaseMessage struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id     *BroadcastID           `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Value  []byte                 `protobuf:"bytes,2,opt,name=value"`
	xxx_hidden_Sender uint32                 `protobuf:"varint,3,opt,name=sender"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PhaseMessage) Reset() {
	*x = PhaseMessage{}
	mi := &file_proto_brb_v1_brb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhaseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseMessage) ProtoMessage() {}

func (x *PhaseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brb_v1_brb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PhaseMessage) GetId() *BroadcastID {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *PhaseMessage) GetValue() []byte {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *PhaseMessage) GetSender() uint32 {
	if x != nil {
		return x.xxx_hidden_Sender
	}
	return 0
}

func (x *PhaseMessage) SetId(v *BroadcastID) {
	x.xxx_hidden_Id = v
}

func (x *PhaseMessage) SetValue(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Value = v
}

func (x *PhaseMessage) SetSender(v uint32) {
	x.xxx_hidden_Sender = v
}

func (x *PhaseMessage) HasId() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Id != nil
}

func (x *PhaseMessage) ClearId() {
	x.xxx_hidden_Id = nil
}

type PhaseMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id    *BroadcastID
	Value []byte
	// sender is trusted by the prototype. A future authenticated transport
	// must bind this claim to the actual peer identity.
	Sender uint32
}

func (b0 PhaseMessage_builder) Build() *PhaseMessage {
	m0 := &PhaseMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Value = b.Value
	x.xxx_hidden_Sender = b.Sender
	return m0
}

var File_proto_brb_v1_brb_proto protoreflect.FileDescriptor

const file_proto_brb_v1_brb_proto_rawDesc = "" +
	"\n" +
	"\x16proto/brb/v1/brb.proto\x12\x06brb.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\fgorums.proto\"A\n" +
	"\vBroadcastID\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\rR\x06origin\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\"a\n" +
	"\fPhaseMessage\x12#\n" +
	"\x02id\x18\x01 \x01(\v2\x13.brb.v1.BroadcastIDR\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\rR\x06sender2\xc0\x01\n" +
	"\tBroadcast\x12:\n" +
	"\x04Send\x12\x14.brb.v1.PhaseMessage\x1a\x16.google.protobuf.Empty\"\x04\x98\xb5\x18\x01\x12:\n" +
	"\x04Echo\x12\x14.brb.v1.PhaseMessage\x1a\x16.google.protobuf.Empty\"\x04\x98\xb5\x18\x01\x12;\n" +
	"\x05Ready\x12\x14.brb.v1.PhaseMessage\x1a\x16.google.protobuf.Empty\"\x04\x98\xb5\x18\x01B6Z/github.com/alkval/gorums-brb/proto/brb/v1;brbv1\x92\x03\x02\b\x02b\beditionsp\xe9\a"

var file_proto_brb_v1_brb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_brb_v1_brb_proto_goTypes = []any{
	(*BroadcastID)(nil),   // 0: brb.v1.BroadcastID
	(*PhaseMessage)(nil),  // 1: brb.v1.PhaseMessage
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_proto_brb_v1_brb_proto_depIdxs = []int32{
	0, // 0: brb.v1.PhaseMessage.id:type_name -> brb.v1.BroadcastID
	1, // 1: brb.v1.Broadcast.Send:input_type -> brb.v1.PhaseMessage
	1, // 2: brb.v1.Broadcast.Echo:input_type -> brb.v1.PhaseMessage
	1, // 3: brb.v1.Broadcast.Ready:input_type -> brb.v1.PhaseMessage
	2, // 4: brb.v1.Broadcast.Send:output_type -> google.protobuf.Empty
	2, // 5: brb.v1.Broadcast.Echo:output_type -> google.protobuf.Empty
	2, // 6: brb.v1.Broadcast.Ready:output_type -> google.protobuf.Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_brb_v1_brb_proto_init() }
func file_proto_brb_v1_brb_proto_init() {
	if File_proto_brb_v1_brb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_brb_v1_brb_proto_rawDesc), len(file_proto_brb_v1_brb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_brb_v1_brb_proto_goTypes,
		DependencyIndexes: file_proto_brb_v1_brb_proto_depIdxs,
		MessageInfos:      file_proto_brb_v1_brb_proto_msgTypes,
	}.Build()
	File_proto_brb_v1_brb_proto = out.File
	file_proto_brb_v1_brb_proto_goTypes = nil
	file_proto_brb_v1_brb_proto_depIdxs = nil
}
