// Code generated by protoc-gen-gorums. DO NOT EDIT.
// versions:
// 	protoc-gen-gorums v0.11.0-devel
// 	protoc            v7.36.0
// source: proto/brb/v1/brb.proto

package brbv1

import (
	gorums "github.com/relab/gorums"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = gorums.EnforceVersion(11 - gorums.MinVersion)
	// Verify that the gorums runtime is sufficiently up-to-date.
	_ = gorums.EnforceVersion(gorums.MaxVersion - 11)
)

// The type aliases below are useful Gorums types that we make accessible
// from generated code. These names therefore become reserved identifiers,
// meaning that proto message types with these names would collide with the
// generated aliases and cause a compile error.
//
// The bundler (gorums_bundle.go) is responsible for discovering these
// aliases and any other identifiers defined herein, and adding them to
// the reserved identifiers list.
//
// If necessary, additional aliases and other identifiers should be added in
// the generator's cmd/protoc-gen-gorums/dev directory, and the bundler will
// automatically discover them and add them to the reserved identifiers list.

type (
	Configuration = gorums.Configuration
	Node          = gorums.Node
	NodeContext   = gorums.NodeContext
	ConfigContext = gorums.ConfigContext
)

// Reference imports to suppress errors if they are not otherwise used.
var _ emptypb.Empty

// Send is a multicast call invoked on all nodes in the configuration in ctx.
// Use gorums.MapRequest to send different messages to each node. No replies are collected.
func Send(ctx *ConfigContext, in *PhaseMessage, opts ...gorums.CallOption) error {
	return gorums.Multicast(ctx, in, "brb.v1.Broadcast.Send", opts...)
}

// Echo is a multicast call invoked on all nodes in the configuration in ctx.
// Use gorums.MapRequest to send different messages to each node. No replies are collected.
func Echo(ctx *ConfigContext, in *PhaseMessage, opts ...gorums.CallOption) error {
	return gorums.Multicast(ctx, in, "brb.v1.Broadcast.Echo", opts...)
}

// Ready is a multicast call invoked on all nodes in the configuration in ctx.
// Use gorums.MapRequest to send different messages to each node. No replies are collected.
func Ready(ctx *ConfigContext, in *PhaseMessage, opts ...gorums.CallOption) error {
	return gorums.Multicast(ctx, in, "brb.v1.Broadcast.Ready", opts...)
}

// Broadcast is the server-side API for the Broadcast Service
type BroadcastServer interface {
	Send(gorums.ServerCtx, *PhaseMessage)
	Echo(gorums.ServerCtx, *PhaseMessage)
	Ready(gorums.ServerCtx, *PhaseMessage)
}

func RegisterBroadcastServer(srv *gorums.Server, impl BroadcastServer) {
	srv.RegisterHandler("brb.v1.Broadcast.Send", func(ctx gorums.ServerCtx, in *gorums.Message) (*gorums.Message, error) {
		req := gorums.AsProto[*PhaseMessage](in)
		impl.Send(ctx, req)
		return nil, nil
	})
	srv.RegisterHandler("brb.v1.Broadcast.Echo", func(ctx gorums.ServerCtx, in *gorums.Message) (*gorums.Message, error) {
		req := gorums.AsProto[*PhaseMessage](in)
		impl.Echo(ctx, req)
		return nil, nil
	})
	srv.RegisterHandler("brb.v1.Broadcast.Ready", func(ctx gorums.ServerCtx, in *gorums.Message) (*gorums.Message, error) {
		req := gorums.AsProto[*PhaseMessage](in)
		impl.Ready(ctx, req)
		return nil, nil
	})
}
